### ISSUE TITLE
[Test case]: Verify that theme can be changed

### ISSUE THREAD

**Issue by OksanaGuz** [Nedilko/weekends#110]
### Description

This TC verifies that user able to change theme from light to dark and from dark to light.
Design - https://www.figma.com/file/k8veH6xqaVXV0DGAtiENFI/weekends?node-id=30%3A4

Preconditions:
- Local storage is empty
- On first application start set Day - Friday, Hour - 18:00.
- Current day is Monday or Tuesday or Wednesday or Thursday or Friday (until 18:00)

### Steps to reproduce

1. Go to https://weekends.nac.in.ua/
2. Click "Apply" button
3. Click on theme toggle switcher on the top right corner
4. Click on theme toggle switcher on the top right corner

### Expected result

1. Modal appears with possibility to choose day and hour left to weekends.
2. Modal disappears. Application name with timer in the center of screen. Application theme is set to light. Toggle position is left.
3. Theme changes from light to dark. Theme toggle changes position from left (off) to right (on).
4. Theme changes from dark to light. Theme toggle changes position from right to left.

**Comment by Nedilko** [comment]
done
@OksanaGuz
