### ISSUE TITLE
[Test case]: Verify that theme remains unchanged after page reload

### ISSUE THREAD

**Issue by OksanaGuz** [Nedilko/weekends#111]
### Description

This TC verifies that user able to change theme from dark to light and set theme remains unchanged after page reload.
Design -
https://www.figma.com/file/k8veH6xqaVXV0DGAtiENFI/weekends?node-id=30%3A49
https://www.figma.com/file/k8veH6xqaVXV0DGAtiENFI/weekends?node-id=30%3A4
Preconditions:
- Not first application load
- Application theme is set to light

### Steps to reproduce

1. Go to https://weekends.nac.in.ua/
2. Click on theme toggle switcher on the top right corner.
3. Reload page.
4. Click on theme toggle switcher on the top right corner.
5. Reload page.
6. Click on theme toggle switcher on the top right corner.
7. Click on 'Gear' (Settings) button in the top left corner.
8. Click on 'Use system theme' switcher.
9. Click on 'Apply' button.
10. Reload page.
11. Change system theme.
12. Reload page.

### Expected result

1. Main page is opened. Application theme is set to light. Toggle position is left.
2. Theme changes from light to dark. Theme toggle changes position from left (off) to right (on).
3. Theme remains unchanged (dark), toggle position is right.
4. Theme changes from dark to light. Theme toggle changes position from right (on) to left (off).
5. Theme remains unchanged (light), toggle position is left.
6. Theme changes from light to dark. Theme toggle changes position from left (off) to right (on).
7. Settings modal appears. Theme switcher in position left.
8. Toggle switcher changes position from off (left) to on (right).
9. Theme adjusts to theme which set in system. Theme toggle (one in the top right corner) disappears.
10. Theme adjusts to theme which set in system.
11. System theme was changed.
12. Theme adjusts to theme which set in system.

**Comment by Nedilko** [comment]
implemented
@OksanaGuz
