### ISSUE TITLE
[Test case]: Verify that application can use system theme

### ISSUE THREAD

**Issue by OksanaGuz** [Nedilko/weekends#112]
### Description

This TC verifies that if user choose "use system theme" function then application theme adjusts to theme which set in system.

 Preconditions:
 - Not first application load
 - Chosen system theme is light
 - Chosen application theme is light
 - "Use system theme" in settings modal set into left position (off)
 

### Steps to reproduce

1. Go to https://weekends.nac.in.ua/
2. Click on 'Gear' (Settings) button in the top left corner.
3. Click on 'Use system theme' switcher.
4. Click on 'Apply' button.
5. Move 'Use system theme' switcher to position 'off'.
6. Click on 'Apply' button.
7. Change system theme to dark.
8. Reload page.
9. Move 'Use system theme' switcher to position 'on'.
10. Click on 'Apply' button.

### Expected result

1. Main page is opened. Application theme is set to light. Toggle position is left.
2. Settings modal appears. Theme switcher in position left.
3. Toggle switcher changes position from off (left) to on (right)
4. Theme adjusts to theme which set in system (light). Theme toggle (one in the top right corner) disappears.
5. Theme switcher in position left
6. Application theme is set to light. Theme toggle (one in the top right corner) appears. Toggle position is left.
7. System theme is changed to dark
8. Application theme is set to light. 
9. Toggle switcher changes position from off (left) to on (right)
10. Theme adjusts to theme which set in system (dark). Theme toggle (one in the top right corner) disappears.

**Comment by Nedilko** [comment]
done as described
@OksanaGuz
