### ISSUE TITLE
[Test case]: Verify that after disabling "use system theme" the theme remains as it was before it

### ISSUE THREAD

**Issue by OksanaGuz** [Nedilko/weekends#113]
### Description

This TC verifies that if user selects a light or dark theme and then applies the "use system theme" feature and after the user disables it, the theme remains as it was before it was applied (light or dark)
Preconditions:
 - Not first application load
 - Chosen application theme is light
 - Chosen system theme is dark
 - "Use system theme" in settings modal set into left position (off)

### Steps to reproduce

1. Go to https://weekends.nac.in.ua/
2. Click on 'Gear' (Settings) button in the top left corner.
3. Click on 'Use system theme' switcher.
4. Click on 'Apply' button.
5. Click on 'Gear' (Settings) button in the top left corner.
6. Click on 'Use system theme' switcher.
7. Click on 'Apply' button.
8. Repeat step 2-7 with chosen application dark theme.

### Expected result

1. Main page is opened. Application theme is set to light. Toggle position is left.
2. Settings modal appears. Theme switcher in position left.
3. Toggle switcher changes position from off (left) to on (right).
4. Theme adjusts to theme which set in system (dark). Theme toggle (one in the top right corner) disappears.
5. Settings modal appears. Theme switcher in position right.
6. Toggle switcher changes position from on (right) to off (left)
7. Application theme is set to light. Theme toggle (one in the top right corner) appears. Toggle position is left.
8. Application theme is set to dark. Theme toggle (one in the top right corner) appears. Toggle position is right.

**Comment by Nedilko** [comment]
implemented
@OksanaGuz
