### ISSUE TITLE
[Test case]: Verify UI page with dark theme

### ISSUE THREAD

**Issue by OksanaGuz** [Nedilko/weekends#115]
### Description

This TC verifies UI of main page, settings modal page when chosen application theme is dark.
The same as #114 but chosen theme is dark
[Design](https://www.figma.com/file/k8veH6xqaVXV0DGAtiENFI/weekends?node-id=30%3A49)
Preconditions:

- Not first application load
- Chosen application theme is dark
- "Use system theme" in settings modal set into left position (off)

### Steps to reproduce

1. Verify all required UI elements on the main page presence.
2. Check all the UI elements for spelling errors.
3. Check the behavior of interactive UI elements.
4. Check the design of all the UI elements.
5. Resize browser window.
6. Click on 'Gear' (Settings) button in the top left corner.
7. Repeat step 1-5.
8. Examine the items of drop-down box fields.

### Expected result

1. All UI elements from the mock-up are present.
2. No spelling errors are found.
3. UI elements respond to pressing as specified in design.
4. All the UI elements look the same as on the design from description.
5. All UI controls are visible.
6. Settings modal appears. Theme switcher in position left.
7. All UI elements correspond to design.
8. Items of drop-down box fields correspond to the requirements in the user story and respond to pressing as specified in design.

**Comment by Nedilko** [comment]
same as [here](https://github.com/Nedilko/weekends/issues/114#issuecomment-1154163346)
@OksanaGuz
