### ISSUE TITLE
[Test case]: Verify application first load

### ISSUE THREAD

**Issue by OksanaGuz** [Nedilko/weekends#117]
### Description

This TC verifies that if user open application at first time 'additional settings modal' is appears with ability to change day and hour.
Preconditions:
 - Local storage is empty.

### Steps to reproduce

1. Go to https://weekends.nac.in.ua/
2. Verify that application start set Day - Friday, Hour - 18:00 by default
3. Verify dropdown 'day'
4. Verify dropdown 'hour'
5. Change day and hour (TD: day ahead from current day, 15:00)
6. Click on 'Apply' button
7. Verify timer estimate.

### Expected result

1. Application page is open. 'Additional settings modal' is appears on the center of the screen.
2. Start set Day - Friday, Hour - 18:00 by default.
3. Day dropdown has all week day ahead from current day, including current day
4. If selected current day, hour dropdown has all day hours ahead from current hour, otherwise, has all day hours in format hh:00
5. Chosen day and hour displays on the specified fields. 
6. Application name and timer is appear. Application theme is set to light by default.
7. Timer started countdown from current day to next day, 15:00.

**Comment by Nedilko** [comment]
implemented without checking:
- Dropdown items to not have previous values
- Timer appear
- Timer started countdown from current day to next day, 15:00.

@OksanaGuz

**Comment by Nedilko** [comment]
added check that Timer appear and has appropriate digit numbers
@OksanaGuz
