### ISSUE TITLE
[Test case]: Verify that application displays time left to chosen day and hour

### ISSUE THREAD

**Issue by OksanaGuz** [Nedilko/weekends#118]
### Description

This TC verify if the timer counts down the time left until the set date in the additional settings modal
Preconditions:

- Local storage is empty.
- Additional settings modal is displays.

### Steps to reproduce

1. Choose day and hour from dropdown list.
2. Click 'Apply' button.

Test Data for step 1.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/kseniasokolova/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/kseniasokolova/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

</head>

<meta charset=utf-8>
<meta charset=utf-8>

<body link="#0563C1" vlink="#954F72">

  | Day | Hour
-- | -- | --
1 | current day | 1 hour ahead current
2 | Sunday | 23:00
3 | Saturday | 00:00

</body>

</html>

### Expected result

1. Chosen day and hour displays is the specified fields.
2. Timer started countdown from current day to chosen day and hour.

**Comment by Nedilko** [comment]
skipped
@OksanaGuz
