### ISSUE TITLE
[Test case]: Verify that application is not support past tense

### ISSUE THREAD

**Issue by OksanaGuz** [Nedilko/weekends#119]
### Description

This TC verifies that there is no ability to choose past day and hour
Preconditions:

- Local storage is empty.
- Additional settings modal is displays.

### Steps to reproduce

1. Click on "Day" dropdown.
2. Click on "Hour" dropdown.
3. Choose current day from "Day" dropdown.
4. Click on "Hour" dropdown.

### Expected result

1. Day dropdown has all week day ahead from current day, including current day. Past days of the week are not shown.
2. 'Hour' dropdown has all day hours in format hh:00 from "00:00" to "23:00".
3. Chosen day displays on the specified field.
4. 'Hour' dropdown has all day hours ahead from current hour to '23:00'.  Past hours of the day are not shown.

**Comment by Nedilko** [comment]
skip
@OksanaGuz
