### ISSUE TITLE
[Test case]: Verify UI settings modal page on application first load 

### ISSUE THREAD

**Issue by OksanaGuz** [Nedilko/weekends#120]
### Description

This TC verifies UI settings modal page on application first load.
Modal must meet [design mockup](https://www.figma.com/file/k8veH6xqaVXV0DGAtiENFI/weekends?node-id=74%3A1070)
Preconditions:

- Local storage is empty.
- Additional settings modal is displays.

### Steps to reproduce

1. Verify all required UI elements on the main page presence.
2. Check all the UI elements for spelling errors.
3. Check the behavior of interactive UI elements.
4. Check the design of all the UI elements.
5. Examine the items of drop-down box fields.
6. Resize browser window.

### Expected result

1. All UI elements from the mock-up are present.
2. No spelling errors are found.
3. UI elements respond to pressing as specified in design.
4. All the UI elements look the same as on the design from description.
5. Items of drop-down box fields correspond to the requirements in the user story and respond to pressing as specified in design.
6. All UI controls are visible.

**Comment by Nedilko** [comment]
done
@OksanaGuz
