### ISSUE TITLE
[Test case]: Verify that digits logically decreases

### ISSUE THREAD

**Issue by OksanaGuz** [Nedilko/weekends#124]
### Description

This TC verifies that when the last right block reaches 0, the previous one logically decreases. Days - 6-1, Hours - 23-0, Minutes - 59-0, Seconds - 59-0

Preconditions:

- Current day is Monday or Tuesday or Wednesday or Thursday or Friday.
- Not first application start

### Steps to reproduce

1. Open settings modal
2. Fill in values:
- Day to current day
- Hour ahead 1 values to current hour
3. Apply settings
4. Observe timer countdown.

### Expected result

1. Settings modal is opened
2. Selected values is shown in specified fields
3. Settings modal is closed. Timer is displayed.
4. Every second, timer updates its values. When block reaches zero (0), it logically changes to lower value. Previous block decreases by one number. When first block reaches zero, it hides.

**Comment by Nedilko** [comment]
implemented
@OksanaGuz
