### ISSUE TITLE
[Test case]: Verify that Greetings text is displayed if countdown is over

### ISSUE THREAD

**Issue by OksanaGuz** [Nedilko/weekends#126]
### Description

This TC verifies that Greetings text is displayed if every digit block reaches zero and countdown is over.
Preconditions: 
- Not first application start
- Selected left time to weeks current day and hour
- Go to app a minute before countdown is over

### Steps to reproduce

1. Observe timer
2. Wait until time reaches 0
3. Take a look to main page

### Expected result

1. Timer has 1 digit block - Seconds
2. Every second timer updates its values.
3. When seconds block reaches zero, it hides and "HAVE A BEER" default Greetings text is displayed on the main page.

**Comment by Nedilko** [comment]
implemented
@OksanaGuz
