### ISSUE TITLE
[Test case]: Verify that user can use settings modal

### ISSUE THREAD

**Issue by OksanaGuz** [Nedilko/weekends#127]
### Description

This TC verifies that user able to choose day and time from setting modal and set Greeting text.
Preconditions:
- Not first app load

### Steps to reproduce

1. Click on 'Gear' (Settings) button in the top left corner.
2. Fill 'Greeting text' input field from 1 to 20 characters(e.g. Dyson styler)
3. Click on Day dropdown list
4. Choose day from dropdown list 
- Monday
- current day
- Sunday
5. Click on Hour dropdown list
6. Choose hour from dropdown list
- 00:00
- 1 hour ahead to current
- 23:00
7. Click on 'Apply' button

### Expected result

1. Settings modal appears.
2. Set text is displayed in the 'Greeting text' input field
3. Dropdown is opened, current day displays on the first place. Range is from current day to Sunday
4. Chosen day is displayed in the Day field
5. Dropdown is opened, If chosen day is current then 1 hour ahead to current displays on the first place. Range from current hour to 23:00. Otherwise the range is from 00:00 to 23:00
6. Chosen hour is displayed in the Hour field
7. Settings modal is closed. Timer has label above timer with text "Time left to weekends". After time is over the set greeting text appears on the screen.

**Comment by Nedilko** [comment]
also added step to check if toggle switcher can change its position on click
@OksanaGuz FYI
