### ISSUE TITLE
[Test case]: Verify settings modal behaviour

### ISSUE THREAD

**Issue by OksanaGuz** [Nedilko/weekends#128]
### Description

This TC verifies that if user doesn't click the Apply button, the filled data is reset
Preconditions:
- Not first app load
- Default Greeting text - Have a beer
- Default day and hour - Friday, 18:00

### Steps to reproduce

1. Click on 'Gear' (Settings) button in the top left corner.
2. Change values Day, Hour and Greeting text.
3. Click on Cancel button
4. Click on 'Gear' (Settings) button in the top left corner.
5. Change values Day, Hour and Greeting text.
6. Click on the area outside settings modal

### Expected result

1. Settings modal appears with default values: Greeting text - Have a beer; day and hour - Friday, 18:00
2. Filled values displays on specified fields
3. Settings modal is closed. Timer countdown to Friday, 18:00
4. Settings modal appears with default values: Greeting text - Have a beer; day and hour - Friday, 18:00
5. Filled values displays on specified fields
6. Settings modal is closed. Timer countdown to Friday, 18:00

**Comment by Nedilko** [comment]
implemented as is
