### ISSUE TITLE
[Test case]: Input fields validation

### ISSUE THREAD

**Issue by OksanaGuz** [Nedilko/weekends#129]
### Description

This TC verifies that user able to choose available days and hours which depends on current day of week and verifies Greeting text field
Preconditions:
- Not first app load
- Current day is Friday; current hour is 13:45

### Steps to reproduce

1. Click on 'Gear' (Settings) button in the top left corner.
2. Fill 'Greeting text' input field following values:
- empty field
- only spaces
3. Click Apply button
4. Fill 'Greeting text' input field
- more than 20 characters
5. Choose day Thursday
6. Choose current day
7. Choose hour - 12:00

### Expected result

1. Settings modal is appears.
2. The field is highlighted with red color.
3. Apply button doesn't allow move further. Setting modal is displayed.
4. There is no ability type more than 20 characters.
5. There is no ability to choose previous day.
6. Chosen day is displayed in the field.
7. There is no ability to choose previous hour.

**Comment by Nedilko** [comment]
not implemented functionality to hide previous days or hours
@OksanaGuz
